name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      - name: Swift version
        run: swift --version
      - name: Build (debug)
        run: swift build --build-tests
      - name: Run tests
        run: swift test --enable-code-coverage

  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build (debug)
        run: swift build --build-tests
      - name: Run tests
        run: swift test --enable-code-coverage
