import Foundation
import Crypto

public struct LoginUserUseCase: Sendable {
    public let userRepository: UserRepository
    
    public init(userRepository: UserRepository) {
        self.userRepository = userRepository
    }
    
    public struct Input: Sendable {
        public let email: String
        public let password: String
        
        public init(email: String, password: String) {
            self.email = email
            self.password = password
        }
    }
    
    public struct Output: Sendable {
        public let user: User
        public let token: String // JWT token, will be generated by infrastructure
        
        public init(user: User, token: String) {
            self.user = user
            self.token = token
        }
    }
    
    public enum LoginError: Error, Equatable, CustomStringConvertible {
        case invalidCredentials
        case userNotFound
        
        public var description: String {
            switch self {
            case .invalidCredentials:
                return "Invalid email or password."
            case .userNotFound:
                return "User not found."
            }
        }
    }
    
    public func execute(input: Input) async throws -> Output {
        // 1. Validate email format
        guard let email = Email(input.email) else {
            throw LoginError.invalidCredentials
        }
        
        // 2. Retrieve user by email
        guard let user = try await userRepository.findByEmail(email) else {
            throw LoginError.userNotFound
        }
        
        // 3. Verify password against stored hash
        guard try Bcrypt.verify(input.password, against: user.passwordHash) else {
            throw LoginError.invalidCredentials
        }
        
        // 4. Generate JWT token (delegated to infrastructure)
        //    This use case only returns the user; token generation will be handled by a separate service
        //    For now, we'll leave token as placeholder but it will be generated in the controller.
        //    We'll refactor later to inject a TokenGenerator protocol.
        
        // Return output (token will be generated by controller/service)
        return Output(user: user, token: "") // placeholder, will be filled later
    }
}
